### ISSUE TITLE
CRASH when using redstone energy block

### ISSUE THREAD

**Issue by Cynix32** [Lupicus/RedstoneExtras#2]
GraalVM Java 8
MC 1.16.5
Forge 36.1.4

RedstoneExtras-1.16.2-1.0.0.7.jar
Mekanism-1.16.5-10.0.21.448.jar

When using the redstone energy block and universal cable from mekanism, it causes a crash

How to replicate:
1. Craft a redstone energy block and place it on the ground.
2. Craft a lever and attach it to redstone energy block.
3. Turn on the lever.
4. Craft a universal cable from mekanism
5. Place the universal cable besides the redstone energy block
6. CRASH!!
(Take note that the world will now become inaccessible due to this crash, unless you remove Redstone Extras Mod)

Here is the crashlog:
https://pastebin.com/b2pmdveK

**Comment by Lupicus** [comment]
Fixed
