### ISSUE TITLE
Enable distribution outside of the CF-OW ecosystem

### ISSUE THREAD

**Issue by infernostars** [Lupicus/RedstoneExtras#3]
because of your [or cf's, sometimes?] decision to opt out to the "allow the distribution of this project outside the curseforge-overwolf ecosystem" toggle, cf is starting to enforce this, so your mod is effectively undownloadable from third party launchers (MultiMC, PolyMC, GDLauncher, ...), which is required/used by some users to get their packs. if you want to keep your mod in packs, it's generally advised to allow this so users don't have to manually download it - thanks!

**Comment by Lupicus** [comment]
My friend is evaluating the impact of making this change, but we currently only support the curse forge app (works fairly well) for people that don't like the website. Supporting third party apps is kind of problematic, almost like not being in those packs (especially true if they are only available from the third party).

**Comment by mactso** [comment]
Hi, I've been investigating this issue.   I'm considering a couple of approaches.  One is to open up a single mod and seeing how this affects us and the other is opening up patreon support to allow particular mods to be open.

Being open source, I'd be fine if the alternative loaders were completely non-profit but all I looked at have ads on the loader or their web site.  Some of them are substantial businesses with tens of thousands of users.  They appear to be using Curseforge storage and bandwidth via a channel that produces no advertising revenue.

Could you explain the upside for supporting these alternative loaders?
