### ISSUE TITLE
1.0.11 redstone energy block doesnt change at all

### ISSUE THREAD

**Issue by TungstenWolf** [Lupicus/RedstoneExtras#4]
right clicking the red stone energy block does nothing to the block

**Comment by TungstenWolf** [comment]
i am retard there are 2 different blocks that look similar

**Comment by Lupicus** [comment]
I might redesign the look.

**Comment by TungstenWolf** [comment]
Yeah, i think just adding a border or some noise to the texture is a simple say to make them look good
